namespace JobHandlerAPI.DTOs
{
    // DTO used when creating a new post
    // Sensitive fields are generated by the server.
    public class CreatePostDto
    {
        public string Title { get; set; }

        public string CompanyName { get; set; }

        public string Link { get; set; }

        public string Status { get; set; }

        public string AdText { get; set; }

        public DateTime ApplicationDate { get; set; }
    }
}
